name: 00 - Workflow Dispatch

on:
  workflow_dispatch:
    inputs:
      input:
        description: "Test"
        required: false
        default: "World"

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Log input parameters from actions # make sure $InputJsonFromMain is added in main workflow as Env variable like- InputJsonFromMain: ${{ toJSON(github.event.inputs) }}
        shell: pwsh
        run: |
          $input = "${{ github.event.inputs }}"
          $input
